auth: tests/scripts/sigterm_wrapper coverage run s_auth/wsgi.py
resource: tests/scripts/sigterm_wrapper coverage run s_resource/wsgi.py
client: tests/scripts/sigterm_wrapper coverage run s_client/wsgi.py
